title: AI Development Blog
author: David Lee
email: lee.yonghee.dev@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  AI 개발 및 프레임워크 분석을 다루는 기술 블로그입니다.
  Rust, Python, AI/ML 프로젝트의 심층 분석과 실무 경험을 공유합니다.
show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--more--> # Custom excerpt separator

# SEO 설정
url: "https://leeyonghe.github.io" # 실제 사이트 URL
baseurl: "/ai-blog" # 저장소 이름이 ai-blog인 경우
lang: ko
locale: ko_KR

# Social media and search optimization
twitter:
  username: # 트위터 사용자명이 있다면 추가
  card: summary_large_image

facebook:
  app_id: # Facebook 앱 ID가 있다면 추가
  publisher: # Facebook 페이지 URL이 있다면 추가

# SEO 태그 설정
seo:
  name: David Lee
  links:
    - https://github.com/leeyonghe
    - https://www.linkedin.com/in/lee-yong-hee-18912454/

# 검색 엔진 최적화
google_analytics: # Google Analytics ID가 있다면 추가 (예: G-XXXXXXXXXX)
google_site_verification: # Google Search Console 인증 코드
naver_site_verification: # 네이버 웹마스터 도구 인증 코드

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: David Lee
  tagline: Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    # twitter: samarsault
    github:  leeyonghe
    linkedIn: in/lee-yong-hee-18912454/
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# GitHub Pages and Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages configuration
remote_theme: plainwhite
destination: _site
source: .
safe: true
incremental: false

# Include only specific directories and files for Jekyll processing
include:
  - _posts/
  - assets/
  - _includes/
  - _layouts/
  - _sass/

# Exclude problematic directories and files
exclude:
  - oxy-cust/
  - oxy-cust/**/*
  - "oxy-cust/**"
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .git/
  - .github/
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - DEPLOYMENT_GUIDE.md
  - "*.gem"
  - "*.gemspec"
  - run.bat
  - push.bat
  - push.sh
