name: Build Jekyll Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # This automatically runs 'bundle install' and caches gems

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Add platform to Gemfile.lock
        run: |
          bundle lock --add-platform x86_64-linux

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --verbose --trace

      - name: Test build artifacts
        run: |
          test -f _site/index.html
          echo "Build successful - _site directory created with $(find _site -name '*.html' | wc -l) HTML files"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jekyll-site
          path: _site/
          retention-days: 7