name: Build Jekyll Site

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false # Disable auto-cache to control manually

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local without 'development test'

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Build site
        run: |
          bundle exec jekyll build --verbose

      - name: Test build artifacts
        run: |
          if [ ! -f "_site/index.html" ]; then
            echo "Error: _site/index.html not found"
            exit 1
          fi
          echo "Build successful - _site directory created with $(find _site -name '*.html' | wc -l) HTML files"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jekyll-site-${{ github.sha }}
          path: _site/
          retention-days: 7

      - name: Test build artifacts
        run: |
          test -f _site/index.html
          echo "Build successful - _site directory created with $(find _site -name '*.html' | wc -l) HTML files"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jekyll-site
          path: _site/
          retention-days: 7